### ISSUE TITLE
Erderakadak harrapatzeko issuea

### ISSUE THREAD

**Issue by ekaitz-zarraga** [ZiTAL/JokoakEuskaraz#2]
1. "Arantza ona ematen dit"
https://github.com/ZiTAL/JokoakEuskaraz/blob/main/Soma/config/lang_main/english.lang#L3386
2. "Arantza txarra ematen dit"
https://github.com/ZiTAL/JokoakEuskaraz/blob/main/Soma/config/lang_main/english.lang#L3654

**Comment by ekaitz-zarraga** [comment]
3. "<dañado>"

**Comment by ekaitz-zarraga** [comment]
4. "Sexua: H/M" -> G edo E izan beharko litzateke

**Comment by ZiTAL** [comment]
konponduta :)
