### ISSUE TITLE
[SOMA] Menua

### ISSUE THREAD

**Issue by Sergio-Muriel** [ZiTAL/JokoakEuskaraz#3]
Ez nago ziur, baina  "Aukerak"   menuan:

 "Zatitua" -> "Jokua" edo zerbait antzekoa?

**Comment by ZiTAL** [comment]
pantallazoren bat edo bidaltzerik?

**Comment by Sergio-Muriel** [comment]
![image](https://github.com/user-attachments/assets/054beae0-c0f4-4110-a7bd-9ef4622dcbee)

Ingelesez "Game" options agertzen da.

**Comment by ZiTAL** [comment]
pull request-ik eitxeko prest?

**Comment by ZiTAL** [comment]
Game Erauntsiako itzultzaileek **JOKAGARRITASUNA** esan didate, ea hau ere aldatzerik duzun haha, eta pull request berri bat bidali, eskerrik asko! @Sergio-Muriel

**Comment by Sergio-Muriel** [comment]
Noski, hemen duzu:
https://github.com/ZiTAL/JokoakEuskaraz/pull/6

Dena branch berean egiten ari naiz.

**Comment by ZiTAL** [comment]
eskerrik asko!
